services:

  backend:
    build:
      context: ./backend
    container_name: moviehub-backend
    ports:
      - "3100:3000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_MOVIE_API_URL: http://localhost:3100
    container_name: moviehub-frontend
    ports:
      - "8100:80"
    depends_on:
      - backend