apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviehub-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviehub-backend
  template:
    metadata:
      labels:
        app: moviehub-backend
    spec:
      containers:
        - name: moviehub-backend
          image: BACKEND_IMAGE
          ports:
            - containerPort: 3000